### PR TITLE
I18n

### PR DESCRIPTION
**Pull request by MoOx**
Current state (proposal)

Homepage /
screen shot 2015-11-19 at 09 13 59

/en/
screen shot 2015-11-19 at 09 14 06

/fr/
screen shot 2015-11-19 at 09 14 11

- I remove some sha blah blah to keep things simple & easy to translate/update.
- I added a link "help us translate" that change depending on the location (light on homepage) and number of posts available
- avatars are missing from the screenshots (firefox full screenshot bug, the avatar are totally ok)
- I fixed the purple/blue color of the links in the screen, but I am too lazy to update the screenshots

What do you think about the layout of the new homepage?
What do you think about the incoming page URL /en/contributing/translate and /fr/contribuer/traduire ?

### CODE REVIEW

**Comment by Uhsac** [comment]
Smaller red part about putaindecode is great, only problem for me is the "more posts" button in homepage that are not aligned (but I don't know if this is possible)

**Comment by MoOx** [comment]
The buttons not aligned might be fixed by using flexbox more :) (note: the "bug" depends of your viewport width)

**Comment by Macxim** [comment]
I really don't think the `/` Homepage should display more than one language.
Keeping in mind internationalization best practices, it is always better to separate localized content.

**Comment by MoOx** [comment]
@Macxim So which language would you like to see on /?
I would go for english.
But Since we don't have lot of posts at the moment, I introduced the latest french posts (but I think we should only do that temporary).

**Comment by Macxim** [comment]
It would be better to decide through a vote.
If I recall correctly, @Nyalab thinks {p!} is first and foremost made up french content and should stay this way (that is, English (and localized) content is optional).
Since we don't have a lot of posts in English or any other localized content for that matter, I think I would go for French.
Maybe at some point, if we get more post in English we could switch.
What do you think @putaindecode/authors?

**Comment by skinnyfoetusboy** [comment]
First and foremost, Putain De Code is a French website, centered around bringing quality content in French.
Hence, making English content be the "default" one would defeat the whole purpose, methinks. That is why I would also push for a rule that would be "no English article as long as a French version isn't provided."

**Comment by MoOx** [comment]
@skinnyfoetusboy this rule (a post MUST HAVE a french version) is not explicit but is a requirement indeed (we discussed about it already).

**Comment by skinnyfoetusboy** [comment]
@MoOx Then you've answered your own question. If a French version is required, that means it IS the main content and the content should default to French :D

**Comment by kud** [comment]
The best way should be to detect the language of the user but not so easy with a static website. Maybe we should give the opportunity to the user to choose what language they want and save it in a cookie. A link will be still available on the website to switch language.

**Comment by MoOx** [comment]
@skinnyfoetusboy This rule (will) exist "just" in order to:
- keep the roots of p! (frenchies)
- promote the fact that all content can be translated

@kud redirection is not a good idea, especially on a website homepage (/). In the current state of my proposal, I think the ability to choose your language is visible enough (in the header + in the footer). Is it?

**Comment by MoOx** [comment]
What about this rule: a post need a minimum of 2 versions (so fr + en, en + fr, en + whatever, whatever + whatever...). This would enforce even more translations.

**Comment by skinnyfoetusboy** [comment]
I don't think it would be a good idea.
You shouldn't have to *enforce* translations, I would rather have them be *encouraged*. 
The only situation where you could have to actually ask for a mandatory translation would be in case of a non-French submission which someone would then have to translate in French.

**Comment by lionelB** [comment]
> Hence, making English content be the "default" one would defeat the whole purpose,

totally agree 
\o\ (frenchforthewin) /o/

**Comment by MoOx** [comment]
The idea of translating some content is to make it more accessible to a larger audience.
It clear that, since I am more confortable with french, I will start my post in french first, then translate them in english (because I can and I want to).
So I think having an homepage in french is not "making content more accessible".
English (in our work) is clearly the most used language, that is why I think we should have the homepage in english. Nobody agree here?

**Comment by MoOx** [comment]
If the majority here wants a homepage in french, I think we could detect browser language and add a message in a banner if browser locale is english...

**Comment by kud** [comment]
This is what I said, yes.

**Comment by skinnyfoetusboy** [comment]
> English (in our work) is clearly the most used language, that is why I think we should have the homepage in english. Nobody agree here?

Yeah and wasn't the original point of pec to make quality content available to french-speaking people?

> If the majority here wants a homepage in french, I think we could detect browser language and add a message in a banner if browser locale is english...

Looks good to me :D

**Comment by revolunet** [comment]
lets make p! the reference for hiqh quality french dev-related content

**Comment by Macxim** [comment]
Isn't it the case already? 😁

**Comment by revolunet** [comment]
it is :)

**Comment by MoOx** [comment]
So what about this?

screen shot 2015-11-20 at 07 34 06

The banner will be display after 5sec only if you main language is not french (starts with "fr").

**Comment by MoOx** [comment]
Version réversible: si tu es sur un page en anglais et que ta locale est fr, ça te met un message fr

screen shot 2015-11-20 at 08 30 01

**Comment by MoOx** [comment]
Current state of my proposal

screen shot 2015-11-20 at 08 47 46

What do you think about the homepage header?
Is the banner clear and looks good?

**Comment by kud** [comment]
It's pretty good! I like it.

On 20 November 2015 at 08:48, Maxime Thirouin <notifications@github.com>
wrote:

> Current state of my proposal
>
> [image: screen shot 2015-11-20 at 08 47 46]
> <https://cloud.githubusercontent.com/assets/157534/11294388/6781395e-8f63-11e5-9dfc-ef935e43da91.png>
>
> What do you think about the homepage header?
> Is the banner clear and looks good?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/putaindecode/putaindecode.io/pull/536#issuecomment-158313773>
> .
>



-- 
*Erwann Mest*
kud.io

**Comment by lionelB** [comment]
Love the reversible version ! GG

**Comment by Macxim** [comment]
Nice :+1: 
The first version looked better in my opinion : lighter dark and more padding on the buttons.

**Comment by bloodyowl** [comment]
really nice

**Comment by magsout** [comment]
:+1: good. 

And +1 for version fr design

**Comment by MoOx** [comment]
@Macxim the color is the same, it's just a little bit transparent and on the latest version, the banner is in position absolute, to avoid a move of the content below when the banner appear.
I just changed the color a little and make the buttons smaller only for small screen (they were too big on small screen on the first version).

For the behavior, the first "yes" button redirect, the 2 other (now "no" and "Je comprends pas dsl") hide the banner forever (using localestorage)), I added a cross to hide temporarily.

screen shot 2015-11-21 at 07 54 04

**Pull request merged**
