### PR TITLE
[website] add reviewers management ~ fixes #486

### LINKED ISSUE #486: Add reviewers names in post meta ?
Each reviewers can add a commit in order to add himself in the post reviewers list metadata (eg: after authors). Reviewing a post is a contribution imo.
What do you think ?

### PR DESCRIPTION
**Pull request by Nyalab**

### CODE REVIEW

**Comment by magsout** [comment]
Nice, good job and idea @Nyalab :+1:

**Comment by Macxim** [comment]
Cool stuff @Nyalab :+1:

**Comment by Nyalab** [comment]
i will try to see why appveyor is failing tomorrow

**Comment by MoOx** [comment]
I think reviewers should be in a different places, but maybe that will be too much places to see people?

**Comment by Nyalab** [comment]
Yes, i thought about it, and i thought that we should not begin to make differences between a reviewer, a committer, a typo fixer, ... every bit of help is fine, only the author should be highlighted. But if you have a different opinion, say it.

And i think, i would like to see the author/contributors section at the top of the post, but it has to be reworked and i don't have time for this right now, but i keep that in mind to submit it to you later.

**Comment by MoOx** [comment]
> every bit of help is fine

True say. So your solution lgtm.

>  i would like to see the author/contributors section at the top of the post

Not sure it's a good idea. When you start reading a post, you don't care who write it (at least at first).

**Comment by MoOx** [comment]
I see a bug on your screen: we can see "3 contributeurs sur cette page", with 4 avatars.

**Comment by MoOx** [comment]
lgtm.

**Pull request merged**
