### PR TITLE
Design fixes

### PR DESCRIPTION
**Pull request by bloodyowl**

### CODE REVIEW

**Comment by MoOx** [comment]
As screenshot might be nice to easily review the change ;)

Sounds good to me, but not sure about the "logo". Btw is this a logo?
I would like your input on #541 because it's kind of related.

**Comment by bloodyowl** [comment]
## before

screen shot 2016-06-14 at 14 01 33
screen shot 2016-06-14 at 14 01 38

## after

screen shot 2016-06-14 at 14 04 03
screen shot 2016-06-14 at 14 04 08

**Comment by MoOx** [comment]
lgtm

**Comment by lionelB** [comment]
lgtm!

**Comment by lionelB** [comment]
rebase needed ?

**Pull request merged**
