### PR TITLE
Post: Dependency injection with PHP (english translation)

### PR DESCRIPTION
**Pull request by neemzy**
I delivered

### CODE REVIEW

**Comment by MoOx** [comment]
Will review an merge after the current "rush" (so probably in january)

**Comment by neemzy** [comment]
Suits me! Hang in there :)

**Comment by MoOx** [comment]
Will review asap, sorry for the delay.

**Comment by Macxim** [comment]
Just reviewed. Looks good to me :+1:

**Comment by MoOx** [comment]
Could you rebase please? A recent optimization have changed the entire git history. Sorry for that. Thanks in advance :)

**Comment by MoOx** [comment]
Nevermind. We have probably fucked up all PR. Will cherry-pick to handle this.

**Comment by neemzy** [comment]
Haha, yeah, seems like a nice lil' mess. Enjoy!

**Comment by Nyalab** [comment]
Following a bunch of optimizations for the repository, you have to update your PR in order to be mergeable

Can you do something like this please? (omit the first line you already have the putaindecode main repo in the `upstream` remote)

```sh
git remote add upstream git@github.com:putaindecode/putaindecode.io.git
git fetch upstream
git reset --hard upstream/master
git cherry-pick 673b214780ef1073b90b274128c310d9a549faa7
git push -f origin post.en.injection-dependances
```

**Comment by neemzy** [comment]
There you go.

**Comment by Nyalab** [comment]
perfect! you rock! :guitar: :clap:

**Comment by magsout** [comment]
LGTM :shipit:

**Comment by magsout** [comment]
thanks a lot @neemzy for your job

**Comment by MoOx** [comment]
lgtm.

**Comment by neemzy** [comment]
LGBT.

**Pull request merged**
