### PR TITLE
Use system font

### LINKED ISSUE #462: Change fonts
Je suis de moins en moins fan des fontes du site. Surtout celle du titre.

Je n'ai pas encore de proposition mais j'aimerais si possible que l'on en discute.

@bloodyowl propose `Seravek` qui est mieux à mon sens que ce que l'on a actuellement.

screen shot 2015-06-16 at 16 00 19

### PR DESCRIPTION
**Pull request by MoOx**
Close #462 

Preview on OS X El Capitan

screen shot 2015-11-21 at 09 15 18

Obviously this will looks different depending on your OS.

### CODE REVIEW

**Comment by Uhsac** [comment]
Great !

**Comment by magsout** [comment]
LGTM for Mac OS. Just curious about Windows

**Comment by MoOx** [comment]
Maybe we should consider fix the font for "Putain de code !" in the header. I just opened a new issue for that #541.

**Comment by Macxim** [comment]
Alright, why not. :shipit:

**Comment by Nyalab** [comment]
not a big fan of it, i would just use it within the posts content, not for the entirety of the website

**Comment by MoOx** [comment]
I will try to push a screenshot with Avenir for heading and system for the rest.

**Comment by Nyalab** [comment]
i still don't like it, have you changed your mind?

**Comment by MoOx** [comment]
See my last comment, I just haven't taken the time. I will.

**Comment by Nyalab** [comment]
(i know i just wrote it as a reminder to bother you :laughing: :laughing: :laughing:)

**Comment by MoOx** [comment]
Need to cherry pick and force push.

**Comment by MoOx** [comment]
Updated with the current font for title with more fallbacks for Windows.

(Note: this PR has been rebased on #644 because I am lazy so will be merged after.)

screen shot 2016-02-29 at 11 17 22
screen shot 2016-02-29 at 11 17 33

**Comment by MoOx** [comment]
plz review :)

**Comment by Nyalab** [comment]
we need a bot that posts on discord as soon as a "review needed" label is applied :wink:

**Comment by magsout** [comment]
@MoOx you just keep initial font for title and added new font for the rest of website ?

**Comment by MoOx** [comment]
yeah, as discussed earlier (no system font for titles)

**Comment by magsout** [comment]
to be sure, I don't miss something, anyway, LGTM.. :shipit:

**Comment by Nyalab** [comment]
i don't want to be a pain in the ass but i find it way less readable... :disappointed: don't you?

**Comment by MoOx** [comment]
Habit?

**Comment by Nyalab** [comment]
i don't really know, i find the letter way too much spaced between themselves, and the shapes are way too rounded but maybe that's my eyes, maybe ask for someone else input on this

**Comment by magsout** [comment]
@Nyalab

**Comment by MoOx** [comment]
@Nyalab how do you feel the font here http://moox.io/statinamic/ ?
It's the same. I have to admit that on our website it feels different, but I think it's because of the habit. Since the font is the same on statinamic website.

**Comment by MoOx** [comment]
I found the "issue". -webkit-font-smoothing: antialiased;
I removed it, here are some screens:

screen shot 2016-03-01 at 14 43 38
screen shot 2016-03-01 at 14 43 15

I have used the antialiased thing on heading, but not for body font.

**Comment by magsout** [comment]
@Nyalab what do you think now ?

**Comment by Nyalab** [comment]
still not convinced, but since i am the only one, i bow to the democracy

**Comment by MoOx** [comment]
@Nyalab FYI, current font depends on the OS so it's probably ok on OS X and Windows, but for the other... No idea.

Merging now and if people are not happy, please tell us.

**Comment by magsout** [comment]
@Nyalab 
love democracy

giphy

**Pull request merged**
