### PR TITLE
[website] delete crew references ~ fixes #559

### LINKED ISSUE #559: Remove "crew" prop from author json files ?
Because we don't use it.

### PR DESCRIPTION
**Pull request by Nyalab**

### CODE REVIEW

**Comment by magsout** [comment]
:100:  :+1:

**Comment by MoOx** [comment]
"Need review", not "need revision" :)

**Comment by MoOx** [comment]
lgtm.

**Comment by Nyalab** [comment]
thanks.

names are confusingly close, we had the same problem at work, to avoid this problem, let's change the label to "needs more work" or "needs changes"

**Comment by MoOx** [comment]
ok for "needs changes". Done.

**Pull request merged**
