### PR TITLE
[Website] Remove unnecessary 'extends Component' ~ fixes #510

### LINKED ISSUE #510: Use stateless function for react component that don't have a state
Ref #503

### PR DESCRIPTION
**Pull request by Nyalab**
we also get the reading time back

### CODE REVIEW

**Comment by MoOx** [comment]
Easier to review with [?w=1](https://github.com/putaindecode/putaindecode.io/pull/631/files?w=1)

**Comment by Nyalab** [comment]
please review or i merge it soon (this brings us some features back like the display of the reading time, the author section, and so on ...)

**Comment by Nyalab** [comment]
and it blocks me for #486

**Comment by magsout** [comment]
LGTM :+1:

**Comment by MoOx** [comment]
PLEASE FUCKING CHERRY-PICK AND FORCE PUSH.

**Comment by MoOx** [comment]
:+1:

**Pull request merged**
