### PR TITLE
Post: es6 proxies

### PR DESCRIPTION
**Pull request by DavidBruant**
It's a first draft open for review.
I haven't looked at styling conventions yet.
I'm happy to make any change you'd deem necessary.

The article is a bit long at times, but the topic is itself hairy. As I suggested in my comment in #553, maybe this article covers the Reflect API enough (it's hard to distangle both topics as explained in the post)

### CODE REVIEW

**Comment by magsout** [comment]
@DavidBruant top l'article. J'adore ton style d'écriture. J'ai trop rien à redire sur le fond, ça me parait très clair et nickel comme ça.

Pour la forme, si tu peux squash tes commit en un seul, et ajouter une petite bio ? 

Merci pour ton contribution.

**Comment by MoOx** [comment]
Post is crystal clear.
Just some details:
- for the date please use 2015-12-18 (we are late on our calendar :/ )
- line max length: 80 chars (feel free to use something like https://atom.io/packages/line-breaker to make this easy - or we can handle it)
- you can squash your commit with a simple name like "Post es6 proxies" and add a bio like the others https://github.com/putaindecode/putaindecode.io/tree/master/content/authors

With that we will be happy to merge this article and release it today :)

**Comment by DavidBruant** [comment]
Thanks ^^

Ok, doing it now.

**Comment by DavidBruant** [comment]
Done all the things. If there is nothing else, I think it can be merged.

Thanks!

**Comment by magsout** [comment]
:+1: thanks @DavidBruant

**Pull request merged**
