### PR TITLE
putaindecode.io

### PR DESCRIPTION
**Pull request by MoOx**
- [x] use statinamic instead of metalsmith
- [x] merge translation PR posts
- [x] change posts tree
- [x] remove all references to putaindecode.fr (look for `](http://putaindecode.fr/`)
- [x] update previous posts link in posts themselves (look for `](/posts/`)
- [x] remove all useless `route:` metadata
- [x] fix "Articles" and similar links
- [x] check DNS
- [x] add redirection in putaindecode.io repo for /tab to http://tab.putaindecode.io/
- [x] .fr on an Apache instance to rewrite .fr/* -> .io/fr/* (and respect according to recent tree changes)
- [x] update repo reference to putaindecode/putaindecode.io
- [x] update travis and appveyor when repo is changed
- [x] drop https://github.com/putaindecode/putaindecode.github.io repo
- [x] update CNAME to putaindecode.io
- [ ] rename http://putaindecode.io/tab/ to http://tab.putaindecode.io/ (CNAME)
- [x] merge !
- [ ] Run Disqus crawler to update 301 urls https://putaindecode.disqus.com/admin/discussions/migrate/
- [ ] check 404 on putaindecode.fr and putaindecode.io with Integrity.app

---

This PR is just a start for now, but since I have planned a lot of url changes, I would like every authors to give their thoughts if they are not happy with the following changes.

_Note that nothing is sealed_: **until this PR is merged, changes or url updates are possible.**

When we will merge this, `putaindecode.fr` will be routed to an apache instance in order to handle http redirections the right way :)

### CODE REVIEW

**Comment by Macxim** [comment]
```
.fr/posts/      shell/utilitaires-ligne-commande
.io/fr/articles/npm/utilitaire-cli ?
```
Overviews or statements highly relative to time of writing
```
.fr/posts/      js/etat-lieux-js-modulaire-front
.io/fr/news/2014/12/15/etat-lieux-js-modulaire-front

.fr/posts/      frontend/se-mettre-au-frontend-en-2014-par-ou-commencer
.io/fr/news/2014/05/15/se-mettre-au-frontend-en-2014

.fr/posts/      table-ronde/bonnes-pratiques-et-organisation-css-html
.io/fr/news/2014/05/05/table-ronde-3
```

No idea at the moment
```
.fr/posts/      js/externalinterface-call-flash-backbone-toute-une-histoire
.fr/posts/      hack/twitter-comme-lecteur-de-flux
.fr/posts/      html/hache-the-aime-elle-vous-dites
```

**Comment by magsout** [comment]
>.fr/posts/
.io/fr/articles/

:+1: 


>.io/fr/news/2014/12/15/etat-lieux-js-modulaire-front

Add a date for this kind of article is a very good idea. Goog catch @MoOx  

>.io/fr/articles/npm/utilitaire-cli ?

:+1:

**Comment by Uhsac** [comment]
This is nice !

**Comment by lionelB** [comment]
Don't see my post on array.reduce.
Except that, it's ok for me

**Comment by MoOx** [comment]
@lionel because url is already ok !

**Comment by MoOx** [comment]
Not sure for having some posts as news but we definitly need a way to mark those as "probably outdated" after a certain period of time. What about an extra field?

**Comment by Uhsac** [comment]
Not possible to do that with last commit about this post age ? Seems complicated

**Comment by MoOx** [comment]
I have will add some renaming:

```
.fr/posts/      shell/utilitaires-ligne-commande
.io/fr/articles/npm/utilitaire-cli

.fr/posts/      js/externalinterface-call-flash-backbone-toute-une-histoire
.io/fr/articles/flash/bug-externalinterface-call-backbone

.fr/posts/      html/hache-the-aime-elle-vous-dites
.io/fr/articles/html/

.fr/posts/      hack/twitter-comme-lecteur-de-flux
.io/fr/articles/twitter/comme-lecteur-de-flux

.fr/posts/      frontend/se-mettre-au-frontend-en-2014-par-ou-commencer
.io/fr/articles/frontend/2014-se-mettre-au-frontend

.fr/posts/      js/etat-lieux-js-modulaire-front
.io/fr/articles/frontend/2015-etat-lieux-javascript-modulaire
```

Does this looks good to you?
Only one left that I don't know where to place: `.fr/posts/table-ronde/bonnes-pratiques-et-organisation-css-html`. I even thinking about deleting it (using an http "gone" code) because the content is not even relevant today (or at least is not a awesome content imo). Or we can make an exception and place this in the news section (but this also seems wrong to me). I think we should not do this kind of pot-pourri in the future (note: nobody tried to make one). @kud since you are the author of this "post", what is your opinion about this?

**Comment by MoOx** [comment]
I think I got something for this post

```
.fr/posts/      table-ronde/bonnes-pratiques-et-organisation-css-html
.io/fr/evenements/2014/05/table-ronde-bonnes-pratiques-et-organisation-css-html
or 
.io/fr/evenements/2014/05/table-ronde-3
or 
.io/fr/evenements/2014/05/putainde-table-ronde
```

which one?

**Comment by magsout** [comment]
>.io/fr/evenements/2014/05/table-ronde-3
or 

good for me

**Comment by magsout** [comment]
👍

**Comment by MoOx** [comment]
Thanks to everyone involved in this !

**Comment by MoOx** [comment]
For the record, I used the following `.htaccess`:

```
RewriteEngine On

RewriteRule ^projets - [G]

RewriteRule ^posts/ci/introduction http://putaindecode.io/fr/articles/ci [R=301,L]
RewriteRule ^posts/ci/le-deploiement-continu http://putaindecode.io/fr/articles/ci/deploiement-continu [R=301,L]
RewriteRule ^posts/backend/golang-structurer-revel-et-mgo http://putaindecode.io/fr/articles/go/structure-revel-mgo [R=301,L]
RewriteRule ^posts/backend/premiers-pas-avec-ruby http://putaindecode.io/fr/articles/ruby/premiers-pas [R=301,L]
RewriteRule ^posts/backend/ruby-dependances-et-projet http://putaindecode.io/fr/articles/ruby/bundler [R=301,L]
RewriteRule ^posts/bug-webcompat http://putaindecode.io/fr/articles/webcompat [R=301,L]
RewriteRule ^posts/css/mise-en-place-autoprefixer http://putaindecode.io/fr/articles/css/autoprefixer/mise-en-place [R=301,L]
RewriteRule ^posts/css/comment-en-finir-avec-les-prefixes http://putaindecode.io/fr/articles/css/autoprefixer [R=301,L]
RewriteRule ^posts/css/introduction-a-cssnext http://putaindecode.io/fr/articles/css/preprocesseurs/cssnext [R=301,L]
RewriteRule ^posts/css/le-guide-complet-pour-centrer-en-css http://putaindecode.io/fr/articles/css/centrer [R=301,L]
RewriteRule ^posts/css/le-point-sur-les-preprocesseurs http://putaindecode.io/fr/articles/css/preprocesseurs [R=301,L]
RewriteRule ^posts/css/les-grilles-en-inline-block http://putaindecode.io/fr/articles/css/grilles/inline-block [R=301,L]
RewriteRule ^posts/css/les-post-processeurs http://putaindecode.io/fr/articles/css/preprocesseurs/post-processeurs [R=301,L]
RewriteRule ^posts/css/preprocesseur-a-la-carte http://putaindecode.io/fr/articles/css/preprocesseurs/a-la-carte [R=301,L]
RewriteRule ^posts/css/petite-definition-bem http://putaindecode.io/fr/articles/css/bem [R=301,L]
RewriteRule ^posts/css/du-css-evolutif http://putaindecode.io/fr/articles/css/bem/maintenance-evolutivite [R=301,L]
RewriteRule ^posts/docker/introduction-a-docker http://putaindecode.io/fr/articles/docker [R=301,L]
RewriteRule ^posts/docker/les-dockerfiles http://putaindecode.io/fr/articles/docker/dockerfile [R=301,L]
RewriteRule ^posts/env/la-puissance-de-dnsmasq http://putaindecode.io/fr/articles/dnsmasq [R=301,L]
RewriteRule ^posts/env/semver-c-est-quoi http://putaindecode.io/fr/articles/semver [R=301,L]
RewriteRule ^posts/env/vagrant-enlarge-your-vm http://putaindecode.io/fr/articles/vagrant [R=301,L]
RewriteRule ^posts/frontend/comment-deboguer-du-web-sur-tablettes-et-telephones http://putaindecode.io/fr/articles/devtools/deboguer-tablettes-telephones [R=301,L]
RewriteRule ^posts/frontend/creez-vos-iconfonts-avec-gulp-iconfont http://putaindecode.io/fr/articles/js/gulp/icon-fonts [R=301,L]
RewriteRule ^posts/frontend/npm-comme-package-manager-pour-le-front-end http://putaindecode.io/fr/articles/npm/frontend [R=301,L]
RewriteRule ^posts/git/boutez-les-bugs-domptez-votre-historique http://putaindecode.io/fr/articles/git/log-bisect-rebase-reflog [R=301,L]
RewriteRule ^posts/git/versionner-avec-git http://putaindecode.io/fr/articles/git [R=301,L]
RewriteRule ^posts/github-pages/introduction http://putaindecode.io/fr/articles/github/pages/site-web-gratuit [R=301,L]
RewriteRule ^posts/ci/webhooks-github http://putaindecode.io/fr/articles/github/webhooks [R=301,L]
RewriteRule ^posts/js/browserify-all-the-things http://putaindecode.io/fr/articles/js/browserify [R=301,L]
RewriteRule ^posts/webpack/premier-exemple http://putaindecode.io/fr/articles/js/webpack/premier-exemple [R=301,L]
RewriteRule ^posts/webpack http://putaindecode.io/fr/articles/js/webpack [R=301,L]
RewriteRule ^posts/js/debuter-avec-ember http://putaindecode.io/fr/articles/js/ember [R=301,L]
RewriteRule ^posts/js/premiere-app-ember http://putaindecode.io/fr/articles/js/ember/premiere-app/1 [R=301,L]
RewriteRule ^posts/js/premiere-app-ember-suite http://putaindecode.io/fr/articles/js/ember/premiere-app/2 [R=301,L]
RewriteRule ^posts/js/flux-qu-est-ce-c-est http://putaindecode.io/fr/articles/js/flux [R=301,L]
RewriteRule ^posts/js/implementer-flux http://putaindecode.io/fr/articles/js/flux/implementer [R=301,L]
RewriteRule ^posts/js/introduction-a-reactjs http://putaindecode.io/fr/articles/js/react/ [R=301,L]
RewriteRule ^posts/js/reactjs-et-rendu-serverside http://putaindecode.io/fr/articles/js/react/cote-serveur [R=301,L]
RewriteRule ^posts/js/premiers-pas-avec-grunt http://putaindecode.io/fr/articles/js/grunt [R=301,L]
RewriteRule ^posts/js/utiliser-react-en-moteur-de-templates http://putaindecode.io/fr/articles/js/react/utiliser-en-moteur-de-templates [R=301,L]
RewriteRule ^posts/js/introduction-gulp http://putaindecode.io/fr/articles/js/gulp [R=301,L]
RewriteRule ^posts/js/introduction-au-testing-js-front http://putaindecode.io/fr/articles/js/tests/frontend [R=301,L]
RewriteRule ^posts/nodejs/napa-ou-comment-telecharger-package-napa-package-json http://putaindecode.io/fr/articles/npm/napa [R=301,L]
RewriteRule ^posts/nodejs/npm-choisir-version http://putaindecode.io/fr/articles/npm/versions-dependances [R=301,L]
RewriteRule ^posts/shell/apprendre-les-makefiles http://putaindecode.io/fr/articles/make [R=301,L]
RewriteRule ^posts/shell/maitriser-les-redirections-shell http://putaindecode.io/fr/articles/shell/redirections [R=301,L]
RewriteRule ^posts/sublime-text/sublime-text-et-markdown http://putaindecode.io/fr/articles/sublime-text/markdown [R=301,L]
RewriteRule ^posts/vim/il-demarre-vim-par-erreur-ce-qui-se-passe-ensuite-est-tout-simplement-bluffant http://putaindecode.io/fr/articles/vim/ [R=301,L]
RewriteRule ^posts/shell/utilitaires-ligne-commande http://putaindecode.io/fr/articles/npm/utilitaire-cli [R=301,L]
RewriteRule ^posts/js/externalinterface-call-flash-backbone-toute-une-histoire http://putaindecode.io/fr/articles/flash/bug-externalinterface-call-backbone [R=301,L]
RewriteRule ^posts/html/hache-the-aime-elle-vous-dites http://putaindecode.io/fr/articles/html/ [R=301,L]
RewriteRule ^posts/hack/twitter-comme-lecteur-de-flux http://putaindecode.io/fr/articles/twitter/comme-lecteur-de-flux [R=301,L]
RewriteRule ^posts/frontend/se-mettre-au-frontend-en-2014-par-ou-commencer http://putaindecode.io/fr/articles/frontend/2014-se-mettre-au-frontend [R=301,L]
RewriteRule ^posts/js/etat-lieux-js-modulaire-front http://putaindecode.io/fr/articles/frontend/2015-etat-lieux-javascript-modulaire [R=301,L]
RewriteRule ^posts/table-ronde/bonnes-pratiques-et-organisation-css-html http://putaindecode.io/fr/evenements/2014/05/table-ronde-3 [R=301,L]

RewriteRule ^posts/comment-contribuer http://putaindecode.io/fr/contribuer [R=301,L]

RewriteRule ^posts/(.*)$ http://putaindecode.io/fr/articles/$1 [R=301,L]

RewriteRule ^feed.xml http://putaindecode.io/feed.xml [R=301,L]

RewriteRule ^$ http://putaindecode.io/ [R=301,L]

RewriteRule ^(.*)$ http://putaindecode.io/fr/$1 [R=301,L]
```

**Comment by Macxim** [comment]
:+1:

**Pull request merged**
