### PR TITLE
Strict mode clarification

### PR DESCRIPTION
**Pull request by ooflorent**
According to MDN:

> The bodies of class declarations and class expressions are executed in strict mode.

### CODE REVIEW

**Comment by bloodyowl** [comment]
thanks for this !

**Comment by MoOx** [comment]
Should have been merged if EN modification too...

**Comment by ooflorent** [comment]
By the way guys you could also update the English version yourselves.

-- 
Florent Cailhol

**Comment by MoOx** [comment]
That why I didn't merge yet...

**Comment by MoOx** [comment]
And by the way dude, there is no "yourselves". You are putaindecode. Putaindecode is everybody.

**Comment by Nyalab** [comment]
better have one PR than none :)

**Pull request merged**
